In [6]:
# Import package.
import pandas as pd

# Load the csv data using pd.read_csv.
products = pd.read_csv('products.csv')

# View the shape of DataFrame.
print(products.shape)

# View the DataFrame.
products.head()

(3945, 2)

  StockCode                  Description
0     10002   INFLATABLE POLITICAL GLOBE
1     10080     GROOVY CACTUS INFLATABLE
2     10120                 DOGGY RUBBER
3    10123C         HEARTS WRAPPING TAPE
4    10124A  SPOTS ON RED BOOKCOVER TAPE

In [11]:
# Products containing the word "fire". 

# Create a user-defined function
def contains_fire(a):
    """ does the product contain fire? """
    b = a.lower()
    return "fire" in b

# View the output.
print(contains_fire(a="Fire polished glass bracelet red"))
print(contains_fire(a="fire polished glass bracelet red"))
print(contains_fire(a="Enamel fire bucket cream"))
print(contains_fire(a="Enamel flower jug cream"))

True
True
True
False

In [12]:
# Use the apply() function.
fire_products = products['Description'].apply(contains_fire)

# Filter the DataFrame.
products[fire_products]

     StockCode                          Description
1318     22428             ENAMEL FIRE BUCKET CREAM
3033    84569B       PACK 3 FIRE ENGINE/CAR PATCHES
3626    90039A     FIRE POLISHED GLASS BRACELET RED
3627    90039B  FIRE POLISHED GLASS BRACELET MONTAN
3628    90039C   FIRE POLISHED GLASS BRACELET BLACK
3629    90039D   FIRE POLISHED GLASS BRACELET GREEN
3656    90060B       FIRE POLISHED GLASS NECKL GOLD
3657    90060D     FIRE POLISHED GLASS NECKL BRONZE
3658    90060F      FIRE POLISHED GLASS NECKL GREEN

In [14]:
# Products containing the word "candle". 

# Create a user-defined function
def contains_candle(c):
    """ does the product contain candle? """
    d = c.lower()
    return "candle" in d

# View the output.
print(contains_candle(c="Fluted antique candle holder"))
print(contains_candle(c="Fluted antique Candle holder"))
print(contains_candle(c="Candleholder pink hanging heart"))
print(contains_candle(c="Ivory embroided quilt"))

True
True
True
False

In [15]:
# Use the apply() function.
candle_products = products['Description'].apply(contains_candle)

# Filter the DataFrame.
products[candle_products]

     StockCode                         Description
83      17012A  ORIGAMI VANILLA INCENSE/CANDLE SET
84      17012B  ORIGAMI JASMINE INCENSE/CANDLE SET
86      17012D     ORIGAMI ROSE INCENSE/CANDLE SET
87      17012E    ORIGAMI OPIUM INCENSE/CANDLE SET
107     17136A      BLUE STONES ON WIRE FOR CANDLE
...        ...                                 ...
3530    85230A         OPIUM SCENTED VOTIVE CANDLE
3531    85230B      CINNAMON SCENTED VOTIVE CANDLE
3532    85230E      STRAWBRY SCENTED VOTIVE CANDLE
3533    85230F               JASMINE VOTIVE CANDLE
3534    85230G                ORANGE VOTIVE CANDLE

[178 rows x 2 columns]

In [17]:
# Products containing the word "matches". 

# Create a user-defined function
def contains_matches(m):
    """ does the product contain matches? """
    n = m.lower()
    return "matches" in n

# View the output.
print(contains_matches(m="Retrospot small tube matches"))
print(contains_matches(m="Retrospot small tube Matches"))
print(contains_matches(m="Vintage union jack apron"))

True
True
False

In [20]:
# Use the apply() function.
matches_products = products['Description'].apply(contains_matches)

# Filter the DataFrame.
products[matches_products]

    StockCode                      Description
669     21584     RETROSPOT SMALL TUBE MATCHES
670     21586  KINGS CHOICE GIANT TUBE MATCHES
671     21587     COSY HOUR GIANT TUBE MATCHES
672     21588     RETROSPOT GIANT TUBE MATCHES
673     21591      COSY HOUR CIGAR BOX MATCHES
674     21592      RETROSPOT CIGAR BOX MATCHES